/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appinterface;

import auxiliar.AuxiliarMethods;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import noname.DBConnection;
import objects.Alumno;
import objects.ControladorAlumno;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author lucia
 */
public class MainWindow extends javax.swing.JFrame {

    ControladorAlumno contAlumnos;
    ButtonGroup cursosGrupo;
    ButtonGroup asignaturasGrupo;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        getDateTime();
        tabla.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE); //para que cuando se clique un botón, deje de editarse la tabla

        //exclusion de los rdbtn cursos
        cursosGrupo = new ButtonGroup();
        cursosGrupo.add(rdbtnc1);
        cursosGrupo.add(rdbtnc2);
        cursosGrupo.add(rdbtnc3);
        cursosGrupo.add(rdbtnc4);

        //exclusion de los rdbtn asignaturas
        asignaturasGrupo = new ButtonGroup();
        asignaturasGrupo.add(rdbtnam3);

        //TODO: mostrar rdbtn cursos
        this.contAlumnos = new ControladorAlumno();

        //TODO: cargar y mostrar rdbtn asignaturas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombreAsignatura = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        jTextArea2 = new javax.swing.JTextArea();
        btnCalificar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnNuevaTarea = new javax.swing.JButton();
        rdbtnam3 = new javax.swing.JRadioButton();
        rdbtnc2 = new javax.swing.JRadioButton();
        rdbtnc3 = new javax.swing.JRadioButton();
        rdbtnc4 = new javax.swing.JRadioButton();
        rdbtnc1 = new javax.swing.JRadioButton();
        btnGuardarTabla = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainWindow");
        setBounds(new java.awt.Rectangle(450, 50, 0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setName("panelPrincipal"); // NOI18N
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel2Layout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel3.setText("Bienvenido/a, @User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(jLabel3, gridBagConstraints);

        fecha.setText("@Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(fecha, gridBagConstraints);

        hora.setText("@Hora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(hora, gridBagConstraints);

        jLabel6.setText("Tiene tareas por calificar en:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setText("@TareasCalificar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Estas son las asignaturas que más frecuenta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setText("@FreqAsignatura1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel10.setText("@FreqAsignatura2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Cursos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Asignaturas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(jLabel12, gridBagConstraints);

        nombreAsignatura.setText(" ");
        nombreAsignatura.setName("nombreAsignatura"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 16;
        jPanel2.add(nombreAsignatura, gridBagConstraints);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(getBackground());
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Haga clic en un alumno\npara desglosar sus notas.\n");
        jTextArea1.setMaximumSize(new java.awt.Dimension(143, 52));
        jTextArea1.setPreferredSize(new java.awt.Dimension(143, 52));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel2.add(jTextArea1, gridBagConstraints);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos", "Nombre", "1º Trimestre", "2º Trimestre", "3º Trimestre", "Nota media", "Nota final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setColumnSelectionAllowed(true);
        tabla.setMinimumSize(new java.awt.Dimension(500, 80));
        tabla.setName("tabla"); // NOI18N
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        jPanel2.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 29;
        jPanel2.add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 5;
        jPanel2.add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 35;
        jPanel2.add(filler6, gridBagConstraints);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(getBackground());
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Haga clic en un trimestre \npara ver un desglose \nde las notas de todos los alumnos \nen ese trimestre.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(jTextArea2, gridBagConstraints);

        btnCalificar.setText("Calificar tareas o pruebas");
        btnCalificar.setName("btnCalificar"); // NOI18N
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.gridwidth = 5;
        jPanel2.add(btnCalificar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 38;
        gridBagConstraints.gridwidth = 33;
        jPanel2.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 32;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 35;
        jPanel2.add(filler7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        jPanel2.add(filler8, gridBagConstraints);

        btnNuevaTarea.setText("Nueva tarea o prueba");
        btnNuevaTarea.setName("btnNuevaTarea"); // NOI18N
        btnNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTareaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.gridwidth = 7;
        jPanel2.add(btnNuevaTarea, gridBagConstraints);

        rdbtnam3.setText("Matemáticas 3º");
        rdbtnam3.setName("rdbtnam3"); // NOI18N
        rdbtnam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnam3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        jPanel2.add(rdbtnam3, gridBagConstraints);

        rdbtnc2.setText("2º");
        rdbtnc2.setName("rdbtnc2"); // NOI18N
        rdbtnc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        jPanel2.add(rdbtnc2, gridBagConstraints);

        rdbtnc3.setSelected(true);
        rdbtnc3.setText("3º");
        rdbtnc3.setName("rdbtnc3"); // NOI18N
        rdbtnc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        jPanel2.add(rdbtnc3, gridBagConstraints);

        rdbtnc4.setText("4º");
        rdbtnc4.setName("rdbtnc4"); // NOI18N
        rdbtnc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 10;
        jPanel2.add(rdbtnc4, gridBagConstraints);

        rdbtnc1.setText("1º");
        rdbtnc1.setName("rdbtnc1"); // NOI18N
        rdbtnc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        jPanel2.add(rdbtnc1, gridBagConstraints);

        btnGuardarTabla.setText("Guardar tabla");
        btnGuardarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTablaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 34;
        jPanel2.add(btnGuardarTabla, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 26;
        jPanel2.add(filler9, gridBagConstraints);

        getContentPane().add(jPanel2);

        jMenuBar1.setName("menuEditar"); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.setName("menuArchivo"); // NOI18N

        jMenuItem1.setText("Salir");
        jMenuItem1.setName("mnbtnSalir"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenu5.setText("Cursos");
        jMenu5.setName("subMenuCursos"); // NOI18N

        jMenuItem2.setText("Añadir curso...");
        jMenuItem2.setName("mnbtnAnadirCurso"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Editar curso...");
        jMenuItem3.setName("mnbtnEditarCurso"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenu2.add(jMenu5);

        jMenu6.setText("Asignaturas");

        jMenuItem4.setText("Añadir asignatura...");
        jMenuItem4.setName("mnbtnAnadirAsignatura"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Modificar asignatura...");
        jMenuItem5.setName("mnbtnModifAsignatura"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenu2.add(jMenu6);

        jMenu7.setText("Alumnos");

        jMenuItem6.setText("Añadir alumnos...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem7.setText("Borrar alumnos...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vista");
        jMenu3.setName("menuVista"); // NOI18N

        jMenuItem8.setText("Ver colores en tabla");
        jMenuItem8.setName("mnbtnColoresTabla"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenu4.setName("menuAyuda"); // NOI18N

        jMenuItem9.setText("Ver cuadros de ayuda");
        jMenuItem9.setName("mnbtnCuadrosAyuda"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Manual de ayuda");
        jMenuItem10.setName("mnbtnManualAyuda"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Acerca de...");
        jMenuItem11.setName("mnbtnAcercaDe"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MainWindow.this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        try {
            JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

            int returnValue = jfc.showOpenDialog(null);

            File file = null;
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                file = jfc.getSelectedFile();
            }

            FileInputStream fis = new FileInputStream(file);   //obtaining bytes from the file  
            //creating Workbook instance that refers to .xlsx file  
            XSSFWorkbook wb = new XSSFWorkbook(fis);
            XSSFSheet sheet = wb.getSheetAt(0);     //creating a Sheet object to retrieve object  
            Iterator<Row> itr = sheet.iterator();    //iterating over excel file  
            while (itr.hasNext()) {
                Object[] alumno = new Object[4];
                int i = 0;
                Row row = itr.next();
                Iterator<Cell> cellIterator = row.cellIterator();   //iterating over each column  
                while (cellIterator.hasNext()) {
                    Cell cell = cellIterator.next();
                    alumno[i] = cell.toString();
                    i++;
                }
                Alumno a = new Alumno();
                a.setApellidos(alumno[0].toString());
                a.setNombre(alumno[1].toString());
                a.setDni(alumno[2].toString());
                a.setFechaNacimiento(alumno[3].toString());
                a.setIdCurso(getCurso());

                contAlumnos.añadirAlumnoACurso(a, getCurso());
                a.commitNuevoAlumno();
            }
        } catch (Exception e) {
            AuxiliarMethods.showWarning(e.toString());
            //TODO --> si el excel no se ha podido cargar bien, mostrar esto con un mensaje de cómo se debe cargar el excel
            //JOptionPane.showMessageDialog(new JFrame(), "Eggs are not supposed to be green.");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new JFrame(), "Trabajo de Fin de Grado de Lucía Calzado Piedrabuena.\nGrado en Ingeniería Informática.\nUCLM.");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        int pasarAsignatura = 0;
        if (!((pasarAsignatura = getAsignatura()) == 0)) {
            CalificarPruebasWindow ctw = new CalificarPruebasWindow(nombreAsignatura.getText(), pasarAsignatura, getCurso(), contAlumnos);
            ctw.pack();
            ctw.setVisible(true);
        }
    }//GEN-LAST:event_btnCalificarActionPerformed

    private void btnNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTareaActionPerformed
        int pasarAsignatura = 0;
        if (!((pasarAsignatura = getAsignatura()) == 0)) {
            NuevaPruebaWindow ntw = new NuevaPruebaWindow(nombreAsignatura.getText(), pasarAsignatura, getCurso(), contAlumnos);
            ntw.pack();
            ntw.setVisible(true);
            ntw.setMinimumSize(ntw.getSize());
        }

    }//GEN-LAST:event_btnNuevaTareaActionPerformed

    private void rdbtnam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnam3ActionPerformed
        nombreAsignatura.setText(rdbtnam3.getText());
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_rdbtnam3ActionPerformed

    private void rdbtnc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc2ActionPerformed
        // TODO add your handling code here:
        asignaturasGrupo.clearSelection();
    }//GEN-LAST:event_rdbtnc2ActionPerformed

    private void rdbtnc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc3ActionPerformed
        // TODO add your handling code here:
        asignaturasGrupo.clearSelection();
    }//GEN-LAST:event_rdbtnc3ActionPerformed

    private void rdbtnc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc4ActionPerformed
        // TODO add your handling code here:
        asignaturasGrupo.clearSelection();
    }//GEN-LAST:event_rdbtnc4ActionPerformed

    private void rdbtnc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc1ActionPerformed
        // TODO add your handling code here:
        asignaturasGrupo.clearSelection();
    }//GEN-LAST:event_rdbtnc1ActionPerformed

    private void btnGuardarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTablaActionPerformed
        int i, j;

        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        HashMap<Integer, ArrayList<Double>> notaFinal = null;

        for (i = 0; i < tabla.getRowCount(); i++) { //itera sobre los alumnos
            notaFinal = new HashMap<>();
            ArrayList<Double> arrayNotas = new ArrayList<>();
            for (j = 2; j < tabla.getColumnCount(); j++) { //itera sobre las notas
                if (j != 5) { //ignorar la columna nota media
                    if (model.getValueAt(i, j) == null) {
                        arrayNotas.add(0.0);
                    } else {
                        arrayNotas.add(Double.parseDouble((model.getValueAt(i, j)).toString()));
                    }
                }
            }
            notaFinal.put(getAsignatura(), arrayNotas);
            contAlumnos.getAlumnosCurso().get(getCurso()).get(i).setNotasFinales(notaFinal);
            try {
                contAlumnos.updateNotasFinales(getCurso(), i, getAsignatura());
            } catch (SQLException e) {
                AuxiliarMethods.showWarning(e.toString());
            }
        }
        calcularNotasMedias();
    }//GEN-LAST:event_btnGuardarTablaActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int pasarAsignatura = 0;

        if (!((pasarAsignatura = getAsignatura()) == 0)) {
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            if (tabla.getSelectedColumn() == 0) {
                for (Alumno alumno : this.contAlumnos.getAlumnosCurso().get(getCurso())) {
                    if (alumno.getApellidos().equals(model.getValueAt(tabla.getSelectedRow(), 0)) && alumno.getNombre().equals(model.getValueAt(tabla.getSelectedRow(), 1))) {
                        InformeAlumnoWindow iaw = new InformeAlumnoWindow(alumno, pasarAsignatura, getCurso(), contAlumnos);
                        iaw.pack();
                        iaw.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    public int getCurso() {
        //Ver qué curso está seleccionado
        if (rdbtnc1.isSelected()) {
            return 1;
        } else if (rdbtnc2.isSelected()) {
            return 2;
        } else if (rdbtnc3.isSelected()) {
            return 3;
        } else if (rdbtnc4.isSelected()) {
            return 4;
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Selecciona un curso primero.");
        }
        return 0;
    }

    public int getAsignatura() {
        if (rdbtnam3.isSelected()) {
            return 1;
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Selecciona una asignatura primero.");
        }
        return 0;
    }

    public void getDateTime() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        fecha.setText(formatter.format(date));

        //hora que se actualiza sola
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String t = new SimpleDateFormat("HH:mm").format(new Date());
                hora.setText(t);
            }
        }, 0, 1000);
    }

    public void cargarTabla(int curso, int asignatura) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel(); //modelo para introducir filas en la tabla
        model.setRowCount(0);

        //Recogemos datos de la DB
        if (curso != 0 && asignatura != 0) {

            Object[] row = new Object[7]; //matriz para el addRow del modelo de la tabla

            try {
                this.contAlumnos.cargarAlumnosCurso(curso);
            } catch (Exception e) {
                AuxiliarMethods.showWarning(e.toString());
            }

            for (Alumno alumno : this.contAlumnos.getAlumnosCurso().get(curso)) {
                row[0] = alumno.getApellidos();
                row[1] = alumno.getNombre();
                ArrayList<Double> notasFinales = alumno.getNotasFinales().get(asignatura);

                if (notasFinales == null || notasFinales.size() < 4) {
                    row[2] = null;
                    row[3] = null;
                    row[4] = null;
                    row[5] = null;
                    row[6] = null;
                } else {
                    if (notasFinales.get(0) == 0.0) {
                        row[2] = null;
                    } else {
                        row[2] = notasFinales.get(0);
                    }
                    row[2] = ((notasFinales.get(0) != 0.0) ? notasFinales.get(0) : null); //condicion ? cosa_true : cosa_false
                    row[3] = ((notasFinales.get(1) != 0.0) ? notasFinales.get(1) : null); //si la primera nota final es 0.0 metes en row[2] la nota final, si no, null
                    row[4] = ((notasFinales.get(2) != 0.0) ? notasFinales.get(2) : null);
                    row[6] = ((notasFinales.get(3) != 0.0) ? notasFinales.get(3) : null);
                }

                model.addRow(row);
            }
        }
        calcularNotasMedias();
        AuxiliarMethods.ajustarColumnasTabla(tabla); //recalculamos el tamaño de las columnas a su contenido
    }

    public void calcularNotasMedias() {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        int i, j;
        int cont = 0;
        double media = 0;
        ArrayList<Double> arrayNotas = new ArrayList<>();
        NumberFormat formatter = new DecimalFormat("#0.00");

        for (i = 0; i < tabla.getRowCount(); i++) {
            for (j = 2; j < 5; j++) {
                media += ((tabla.getValueAt(i, j) != null) ? Double.parseDouble(tabla.getValueAt(i, j).toString()) : 0.0);
                if (media/3 != 0){
                    tabla.setValueAt(media/3, i, 5);
                }
            }
            media = 0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnGuardarTabla;
    private javax.swing.JButton btnNuevaTarea;
    private javax.swing.JLabel fecha;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel nombreAsignatura;
    private javax.swing.JRadioButton rdbtnam3;
    private javax.swing.JRadioButton rdbtnc1;
    private javax.swing.JRadioButton rdbtnc2;
    private javax.swing.JRadioButton rdbtnc3;
    private javax.swing.JRadioButton rdbtnc4;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
