/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appinterface;

import auxiliar.AuxiliarMethods;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import objects.Alumno;
import controladores.ControladorAlumno;
import java.awt.Font;
import objects.Maestro;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author lucia
 */
public class MainWindow extends javax.swing.JFrame {

    ControladorAlumno contAlumnos;
    Maestro maestro;
    ButtonGroup cursosGrupo;
    ButtonGroup asignaturasGrupo;
    int tamañoLetra;

    /**
     * 
     * @param maestro
     * @param tamañoLetra 
     */
    public MainWindow(Maestro maestro, int tamañoLetra) {
        initComponents();
        getDateTime();
        this.tamañoLetra = tamañoLetra;
        this.maestro = maestro;
        ventormentaPicture.setIcon(new ImageIcon("assets/alliance_logo.png"));
        
        
       try {
           maestro.cargarMaestro();
       } catch (SQLException e){
           AuxiliarMethods.showWarning("No se han podido cargar los datos del maestro.\nMás información: "+e.toString());
       }
        
        lblBienvenida.setText("Bienvenido/a, "+maestro.getNombre());
        lblMaestro.setText("Maestr@: "+maestro.getNombre());

        
        tabla.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE); //para que cuando se clique un botón, deje de editarse la tabla

        //Cambiamos el tamaño de la letra si se ha pedido
        if (tamañoLetra != 0) {
            cambiarTamañoLetra();
        }

        //Buscar los cursos y las asignaturas del maestro
        //exclusión de los rdbtn cursos
        cursosGrupo = new ButtonGroup();
        cursosGrupo.add(rdbtnc1);
        cursosGrupo.add(rdbtnc2);
        cursosGrupo.add(rdbtnc3);
        cursosGrupo.add(rdbtnc4);

        //exclusión de los rdbtn asignaturas
        asignaturasGrupo = new ButtonGroup();
        asignaturasGrupo.add(rdbtnmat3A);
        asignaturasGrupo.add(rdbtnlen3A);
        asignaturasGrupo.add(rdbtnmat3C);
        asignaturasGrupo.add(rdbtnrel4A);
        asignaturasGrupo.add(rdbtncon1A);

        rdbtnmat3A.setEnabled(false);
        rdbtnlen3A.setEnabled(false);
        rdbtnmat3C.setEnabled(false);

        rdbtncon1A.setVisible(false);
        //rdbtnmat3C.setVisible(false);

        //TODO: mostrar rdbtn cursos --> necesario LOGIN
        try {
            this.contAlumnos = new ControladorAlumno();
        } catch (SQLException e) {
            AuxiliarMethods.showWarning(e.toString());
        }

        //TODO: cargar y mostrar rdbtn asignaturas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        lblTareasCalificar = new javax.swing.JLabel();
        lblTareasCalificar1 = new javax.swing.JLabel();
        lblMaestro = new javax.swing.JLabel();
        ventormentaPicture = new javax.swing.JLabel();
        lblCursos = new javax.swing.JLabel();
        lblAsignaturas = new javax.swing.JLabel();
        nombreAsignatura = new javax.swing.JLabel();
        txtHagaClic = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        txtHagaClic2 = new javax.swing.JTextArea();
        btnCalificar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnNuevaTarea = new javax.swing.JButton();
        rdbtnmat3C = new javax.swing.JRadioButton();
        rdbtnc2 = new javax.swing.JRadioButton();
        rdbtnc3 = new javax.swing.JRadioButton();
        rdbtnc4 = new javax.swing.JRadioButton();
        rdbtnc1 = new javax.swing.JRadioButton();
        btnGuardarTabla = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        rdbtnmat3A = new javax.swing.JRadioButton();
        rdbtnlen3A = new javax.swing.JRadioButton();
        rdbtnrel4A = new javax.swing.JRadioButton();
        btnEditarUsuario = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        lblCentro = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        rdbtncon1A = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana principal");
        setBounds(new java.awt.Rectangle(450, 50, 0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setName("panelPrincipal"); // NOI18N
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel2Layout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        jPanel2.setLayout(jPanel2Layout);

        lblBienvenida.setText("Bienvenido/a, @User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(lblBienvenida, gridBagConstraints);

        fecha.setText("@Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(fecha, gridBagConstraints);

        hora.setText("@Hora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(hora, gridBagConstraints);

        lblTareasCalificar.setText("Tiene tareas por calificar en:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblTareasCalificar, gridBagConstraints);

        lblTareasCalificar1.setText("@TareasCalificar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblTareasCalificar1, gridBagConstraints);

        lblMaestro.setText("Maestr@: Lucía Calzado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblMaestro, gridBagConstraints);

        ventormentaPicture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel2.add(ventormentaPicture, gridBagConstraints);

        lblCursos.setText("Cursos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(lblCursos, gridBagConstraints);

        lblAsignaturas.setText("Asignaturas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(lblAsignaturas, gridBagConstraints);

        nombreAsignatura.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        nombreAsignatura.setName("nombreAsignatura"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel2.add(nombreAsignatura, gridBagConstraints);

        txtHagaClic.setEditable(false);
        txtHagaClic.setBackground(getBackground());
        txtHagaClic.setColumns(20);
        txtHagaClic.setRows(5);
        txtHagaClic.setText("Haga clic en un alumno\npara desglosar sus notas.\n");
        txtHagaClic.setMaximumSize(new java.awt.Dimension(143, 52));
        txtHagaClic.setPreferredSize(new java.awt.Dimension(143, 52));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel2.add(txtHagaClic, gridBagConstraints);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos", "Nombre", "1º Trimestre", "2º Trimestre", "3º Trimestre", "Nota media", "Nota final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setColumnSelectionAllowed(true);
        tabla.setMinimumSize(new java.awt.Dimension(500, 80));
        tabla.setName("tabla"); // NOI18N
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        jPanel2.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 8;
        jPanel2.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 33;
        jPanel2.add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 5;
        jPanel2.add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 39;
        jPanel2.add(filler6, gridBagConstraints);

        txtHagaClic2.setEditable(false);
        txtHagaClic2.setBackground(getBackground());
        txtHagaClic2.setColumns(20);
        txtHagaClic2.setRows(5);
        txtHagaClic2.setText("Haga clic en un trimestre \npara ver un desglose \nde las notas de todos los alumnos \nen ese trimestre.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.gridwidth = 11;
        jPanel2.add(txtHagaClic2, gridBagConstraints);

        btnCalificar.setText("Calificar tareas o pruebas");
        btnCalificar.setName("btnCalificar"); // NOI18N
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 40;
        gridBagConstraints.gridwidth = 5;
        jPanel2.add(btnCalificar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 44;
        gridBagConstraints.gridwidth = 37;
        jPanel2.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 39;
        jPanel2.add(filler7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 11;
        jPanel2.add(filler8, gridBagConstraints);

        btnNuevaTarea.setText("Nueva tarea o prueba");
        btnNuevaTarea.setName("btnNuevaTarea"); // NOI18N
        btnNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTareaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 40;
        gridBagConstraints.gridwidth = 7;
        jPanel2.add(btnNuevaTarea, gridBagConstraints);

        rdbtnmat3C.setText("Matemáticas 3ºC");
        rdbtnmat3C.setName("rdbtnmat3C"); // NOI18N
        rdbtnmat3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnmat3CActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(rdbtnmat3C, gridBagConstraints);

        rdbtnc2.setText("4ºA");
        rdbtnc2.setName("rdbtnc2"); // NOI18N
        rdbtnc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 16;
        jPanel2.add(rdbtnc2, gridBagConstraints);

        rdbtnc3.setText("3ºA");
        rdbtnc3.setName("rdbtnc3"); // NOI18N
        rdbtnc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        jPanel2.add(rdbtnc3, gridBagConstraints);

        rdbtnc4.setText("3ºC");
        rdbtnc4.setName("rdbtnc4"); // NOI18N
        rdbtnc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 16;
        jPanel2.add(rdbtnc4, gridBagConstraints);

        rdbtnc1.setText("1ºA");
        rdbtnc1.setName("rdbtnc1"); // NOI18N
        rdbtnc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnc1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        jPanel2.add(rdbtnc1, gridBagConstraints);

        btnGuardarTabla.setText("Guardar tabla");
        btnGuardarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTablaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 40;
        jPanel2.add(btnGuardarTabla, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 32;
        jPanel2.add(filler9, gridBagConstraints);

        rdbtnmat3A.setText("Matemáticas 3ºA");
        rdbtnmat3A.setName("rdbtnam3"); // NOI18N
        rdbtnmat3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnmat3AActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(rdbtnmat3A, gridBagConstraints);

        rdbtnlen3A.setText("Lengua Castellana 3ºA");
        rdbtnlen3A.setName("rdbtnmat3C"); // NOI18N
        rdbtnlen3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnlen3AActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(rdbtnlen3A, gridBagConstraints);

        rdbtnrel4A.setText("Religiones 4ºA");
        rdbtnrel4A.setName("rdbtnmat3C"); // NOI18N
        rdbtnrel4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnrel4AActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(rdbtnrel4A, gridBagConstraints);

        btnEditarUsuario.setText("Editar usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        jPanel2.add(btnEditarUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 25;
        jPanel2.add(filler10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 33;
        jPanel2.add(filler11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 35;
        jPanel2.add(filler12, gridBagConstraints);

        lblCentro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblCentro.setText("C.P. Ventormenta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblCentro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 45;
        jPanel2.add(filler13, gridBagConstraints);

        rdbtncon1A.setText("Conocimiento del Medio 1ºA");
        rdbtncon1A.setName("rdbtnmat3C"); // NOI18N
        rdbtncon1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtncon1AActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(rdbtncon1A, gridBagConstraints);

        getContentPane().add(jPanel2);

        jMenuBar1.setName("menuEditar"); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.setName("menuArchivo"); // NOI18N

        jMenuItem1.setText("Salir");
        jMenuItem1.setName("mnbtnSalir"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenu7.setText("Alumnos");

        jMenuItem6.setText("Añadir alumnos...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem7.setText("Borrar alumnos...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vista");
        jMenu3.setName("menuVista"); // NOI18N

        jMenuItem8.setText("Ver colores en tabla");
        jMenuItem8.setName("mnbtnColoresTabla"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenu4.setName("menuAyuda"); // NOI18N

        jMenuItem9.setText("Ver cuadros de ayuda");
        jMenuItem9.setName("mnbtnCuadrosAyuda"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Manual de ayuda");
        jMenuItem10.setName("mnbtnManualAyuda"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Acerca de...");
        jMenuItem11.setName("mnbtnAcercaDe"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MainWindow.this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int idAsignatura = getAsignatura();
        if (getCurso() != 0 && idAsignatura != 0) {
            try {
                JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

                int returnValue = jfc.showOpenDialog(null);

                File file = null;
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    file = jfc.getSelectedFile();
                }

                FileInputStream fis = new FileInputStream(file);   //obtaining bytes from the file  
                //creating Workbook instance that refers to .xlsx file  
                XSSFWorkbook wb = new XSSFWorkbook(fis);
                XSSFSheet sheet = wb.getSheetAt(0);     //creating a Sheet object to retrieve object  
                Iterator<Row> itr = sheet.iterator();    //iterating over excel file  
                while (itr.hasNext()) {
                    Object[] alumno = new Object[4];
                    int i = 0;
                    Row row = itr.next();
                    Iterator<Cell> cellIterator = row.cellIterator();   //iterating over each column  
                    while (cellIterator.hasNext()) {
                        Cell cell = cellIterator.next();
                        alumno[i] = cell.toString();
                        i++;
                    }
                    Alumno a = new Alumno();
                    a.setApellidos(alumno[0].toString());
                    a.setNombre(alumno[1].toString());
                    a.setDni(alumno[2].toString());
                    a.setFechaNacimiento(alumno[3].toString());
                    a.setIdAlumno(a.commitNuevoAlumno());

                    if (contAlumnos.esOptativa(getAsignatura())) {
                        contAlumnos.añadirAlumnoAAsignatura(a, idAsignatura);
                        contAlumnos.commitAlumnoAsignatura(a, idAsignatura);
                    } else {
                        //se tiene que añadir el alumno a todas las asignaturas del curso actual
                        contAlumnos.añadirAlumnoACurso(a, idAsignatura);
                        contAlumnos.commitAlumnoCurso(a, idAsignatura); //commit el alumno a todas las asignaturas de un curso
                    }

                }
            } catch (SQLIntegrityConstraintViolationException e1) {
                AuxiliarMethods.showWarning("Error.\nDNI del alumno duplicado. Revise el Excel.");
                //TODO --> si el excel no se ha podido cargar bien, mostrar esto con un mensaje de cómo se debe cargar el excel
                //JOptionPane.showMessageDialog(new JFrame(), "Eggs are not supposed to be green.");
            } catch (FileNotFoundException e2) {
                AuxiliarMethods.showWarning("Error.\nNo se encuentra el archivo especificado.");
            } catch (Exception e3) {
                AuxiliarMethods.showWarning(e3.toString());
            }
        }
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new JFrame(), "Trabajo de Fin de Grado de Lucía Calzado Piedrabuena.\nGrado en Ingeniería Informática.\nUCLM.");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        int pasarAsignatura = 0;
        if (!((pasarAsignatura = getAsignatura()) == 0)) {
            CalificarPruebasWindow ctw = new CalificarPruebasWindow(nombreAsignatura.getText(), pasarAsignatura, contAlumnos, tamañoLetra);
            ctw.pack();
            ctw.setVisible(true);
        }
    }//GEN-LAST:event_btnCalificarActionPerformed

    private void btnNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTareaActionPerformed
        int pasarAsignatura = 0;
        if (!((pasarAsignatura = getAsignatura()) == 0)) {
            NuevaPruebaWindow ntw = new NuevaPruebaWindow(nombreAsignatura.getText(), pasarAsignatura, contAlumnos, tamañoLetra);
            ntw.pack();
            ntw.setVisible(true);
            ntw.setMinimumSize(ntw.getSize());
        }

    }//GEN-LAST:event_btnNuevaTareaActionPerformed

    private void rdbtnc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc2ActionPerformed
        //Curso 4ºA
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        asignaturasGrupo.clearSelection();
        rdbtnmat3A.setVisible(false);
        rdbtnlen3A.setVisible(false);
        rdbtnmat3C.setVisible(false);
        rdbtncon1A.setVisible(false);
        rdbtnrel4A.setVisible(true);
    }//GEN-LAST:event_rdbtnc2ActionPerformed

    private void rdbtnc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc3ActionPerformed
        //Curso 3ºA
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        asignaturasGrupo.clearSelection();
        rdbtnmat3A.setVisible(true);
        rdbtnlen3A.setVisible(true);
        rdbtnlen3A.setEnabled(true);
        rdbtnmat3A.setEnabled(true);
        rdbtncon1A.setVisible(false);
        rdbtnmat3C.setVisible(false);

    }//GEN-LAST:event_rdbtnc3ActionPerformed

    private void rdbtnc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc4ActionPerformed
        //Curso 3ºC
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        asignaturasGrupo.clearSelection();
        rdbtnmat3C.setVisible(true);
        rdbtnmat3C.setEnabled(true);
        rdbtnmat3A.setVisible(false);
        rdbtnlen3A.setVisible(false);
        rdbtncon1A.setVisible(false);
    }//GEN-LAST:event_rdbtnc4ActionPerformed

    private void rdbtnc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnc1ActionPerformed
        //Curso 1ºA 
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        asignaturasGrupo.clearSelection();
        rdbtnrel4A.setVisible(false);
        rdbtnmat3A.setVisible(false);
        rdbtnlen3A.setVisible(false);
        rdbtnmat3C.setVisible(false);
        rdbtncon1A.setVisible(true);
    }//GEN-LAST:event_rdbtnc1ActionPerformed

    private void btnGuardarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTablaActionPerformed
        int i, j;

        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        HashMap<Integer, ArrayList<Double>> notaFinal = null;

        for (i = 0; i < tabla.getRowCount(); i++) { //itera sobre los alumnos
            notaFinal = new HashMap<>();
            ArrayList<Double> arrayNotas = new ArrayList<>();
            for (j = 2; j < tabla.getColumnCount(); j++) { //itera sobre las notas
                if (j != 5) { //ignorar la columna nota media
                    if (model.getValueAt(i, j) == null) {
                        arrayNotas.add(0.0);
                    } else {
                        arrayNotas.add(Double.parseDouble((model.getValueAt(i, j)).toString()));
                    }
                }
            }
            notaFinal.put(getAsignatura(), arrayNotas);
            contAlumnos.getAlumnosAsignatura().get(getAsignatura()).get(i).setNotasFinales(notaFinal);
            try {
                contAlumnos.updateNotasFinales(i, getAsignatura());
            } catch (SQLException e) {
                AuxiliarMethods.showWarning(e.toString());
            }
        }
        calcularNotasMedias();
    }//GEN-LAST:event_btnGuardarTablaActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int pasarAsignatura = 0;

        if (!((pasarAsignatura = getAsignatura()) == 0)) {
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            if (tabla.getSelectedColumn() == 0) {
                for (Alumno alumno : this.contAlumnos.getAlumnosAsignatura().get(getAsignatura())) {
                    if (alumno.getApellidos().equals(model.getValueAt(tabla.getSelectedRow(), 0)) && alumno.getNombre().equals(model.getValueAt(tabla.getSelectedRow(), 1))) {
                        InformeAlumnoWindow iaw = new InformeAlumnoWindow(alumno, pasarAsignatura, contAlumnos, tamañoLetra);
                        iaw.pack();
                        iaw.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * Seleccionar botón Matemáticas 3ºA
     *
     * @param evt
     */
    private void rdbtnmat3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnmat3AActionPerformed
        nombreAsignatura.setText(rdbtnmat3A.getText());
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_rdbtnmat3AActionPerformed

    /**
     * Seleccionar botón Matemáticas 3ºC
     *
     * @param evt
     */
    private void rdbtnmat3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnmat3CActionPerformed
        nombreAsignatura.setText(rdbtnmat3C.getText());
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_rdbtnmat3CActionPerformed

    /**
     * Seleccionar botón Lengua 3ºA
     *
     * @param evt
     */
    private void rdbtnlen3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnlen3AActionPerformed
        nombreAsignatura.setText(rdbtnlen3A.getText());
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_rdbtnlen3AActionPerformed

    private void rdbtnrel4AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnrel4AActionPerformed
        nombreAsignatura.setText(rdbtnrel4A.getText());
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_rdbtnrel4AActionPerformed

    private void rdbtncon1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtncon1AActionPerformed
        nombreAsignatura.setText(rdbtncon1A.getText());
        cargarTabla(getCurso(), getAsignatura());
    }//GEN-LAST:event_rdbtncon1AActionPerformed

    /**
     * Devuelve un curso, pero lo uso principalmente para comprobar si se ha
     * seleccionado curso
     *
     * @return el curso seleccionado, o 0 si no hay ninguno
     */
    public int getCurso() {

        if (rdbtnc1.isSelected()) {
            return 1;
        } else if (rdbtnc2.isSelected()) {
            return 4;
        } else if (rdbtnc3.isSelected()) {
            return 3;
        } else if (rdbtnc4.isSelected()) {
            return 3;
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Selecciona un curso primero.");
        }
        return 0;
    }

    /**
     * Devuelve la asignatura seleccionada
     *
     * @return el código de la asignatura o 0 si no hay ninguna seleccionada
     */
    public int getAsignatura() {
        if (rdbtnmat3A.isSelected()) {
            return 131; //Matemáticas de 3ºA
        } else if (rdbtnmat3C.isSelected()) {
            return 133; //Matemáticas de 3ºC
        } else if (rdbtnlen3A.isSelected()) {
            return 331; //Lengua de 3ºA
        } else if (rdbtnrel4A.isSelected()) {
            return 441; //Religiones de 4ºA
        } else if (rdbtncon1A.isSelected()) {
            return 211; //Conocimiento del Medio 1ºA
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Selecciona una asignatura primero.");
        }
        return 0;
    }

    private void getDateTime() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        fecha.setText(formatter.format(date));

        //hora que se actualiza sola
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                String t = new SimpleDateFormat("HH:mm").format(new Date());
                hora.setText(t);
            }
        }, 0, 1000);
    }

    public void cargarTabla(int curso, int asignatura) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel(); //modelo para introducir filas en la tabla
        model.setRowCount(0);

        //Recogemos datos de la DB
        if (curso != 0 && asignatura != 0) {

            Object[] row = new Object[7]; //matriz para el addRow del modelo de la tabla

            try {
                this.contAlumnos.cargarAlumnosAsignatura(asignatura);
            } catch (SQLException e) {
                //AuxiliarMethods.showWarning(e.toString());
                System.out.println(e.toString());
            }

            for (Alumno alumno : this.contAlumnos.getAlumnosAsignatura().get(asignatura)) {
                row[0] = alumno.getApellidos();
                row[1] = alumno.getNombre();
                ArrayList<Double> notasFinales = alumno.getNotasFinales().get(asignatura);

                if (notasFinales == null || notasFinales.size() < 4) {
                    row[2] = null;
                    row[3] = null;
                    row[4] = null;
                    row[5] = null;
                    row[6] = null;
                } else {
                    if (notasFinales.get(0) == 0.0) {
                        row[2] = null;
                    } else {
                        row[2] = notasFinales.get(0);
                    }
                    row[2] = ((notasFinales.get(0) != 0.0) ? notasFinales.get(0) : null); //condicion ? cosa_true : cosa_false
                    row[3] = ((notasFinales.get(1) != 0.0) ? notasFinales.get(1) : null); //si la primera nota final es 0.0 metes en row[2] la nota final, si no, null
                    row[4] = ((notasFinales.get(2) != 0.0) ? notasFinales.get(2) : null);
                    row[6] = ((notasFinales.get(3) != 0.0) ? notasFinales.get(3) : null);
                }

                model.addRow(row);
            }
        }
        calcularNotasMedias();
        AuxiliarMethods.ajustarColumnasTabla(tabla); //recalculamos el tamaño de las columnas a su contenido
    }

    public void calcularNotasMedias() {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        int i, j;
        double media = 0;
        ArrayList<Double> arrayNotas = new ArrayList<>();
        NumberFormat formatter = new DecimalFormat("#0.00");

        for (i = 0; i < tabla.getRowCount(); i++) {
            for (j = 2; j < 5; j++) {
                media += ((tabla.getValueAt(i, j) != null) ? Double.parseDouble(tabla.getValueAt(i, j).toString()) : 0.0);
                if (media / 3 != 0) {
                    //da error si uso el formatter para darle formato a las nuevas medias y que salgan con dos decimales
                    //tabla.setValueAt(formatter.format(media / 3), i, 5);
                    tabla.setValueAt(media / 3, i, 5);
                }
            }
            media = 0;
        }
    }

    private void cambiarTamañoLetra() {
        lblAsignaturas.setFont(new Font(lblAsignaturas.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblBienvenida.setFont(new Font(lblBienvenida.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblCursos.setFont(new Font(lblCursos.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblMaestro.setFont(new Font(lblMaestro.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblTareasCalificar.setFont(new Font(lblTareasCalificar.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblTareasCalificar1.setFont(new Font(lblTareasCalificar1.getFont().getName(), Font.PLAIN, tamañoLetra));
        fecha.setFont(new Font(fecha.getFont().getName(), Font.PLAIN, tamañoLetra));
        hora.setFont(new Font(hora.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblCentro.setFont(new Font(lblCentro.getFont().getName(), Font.ITALIC, tamañoLetra+lblCentro.getFont().getSize()));
        ventormentaPicture.setSize(ventormentaPicture.getWidth() +tamañoLetra, ventormentaPicture.getHeight()+tamañoLetra);
        
        btnCalificar.setFont(new Font(btnCalificar.getFont().getName(), Font.PLAIN, tamañoLetra));
        btnEditarUsuario.setFont(new Font(btnEditarUsuario.getFont().getName(), Font.PLAIN, tamañoLetra));
        btnGuardarTabla.setFont(new Font(btnGuardarTabla.getFont().getName(), Font.PLAIN, tamañoLetra));
        btnNuevaTarea.setFont(new Font(btnNuevaTarea.getFont().getName(), Font.PLAIN, tamañoLetra));
        
        rdbtnc1.setFont(new Font(rdbtnc1.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnc3.setFont(new Font(rdbtnc3.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnc4.setFont(new Font(rdbtnc4.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnc2.setFont(new Font(rdbtnc2.getFont().getName(), Font.PLAIN, tamañoLetra));
        
        rdbtnmat3A.setFont(new Font(rdbtnmat3A.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnmat3C.setFont(new Font(rdbtnmat3C.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnlen3A.setFont(new Font(rdbtnlen3A.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnrel4A.setFont(new Font(rdbtnrel4A.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtncon1A.setFont(new Font(rdbtncon1A.getFont().getName(), Font.PLAIN, tamañoLetra));
        
        jMenu1.setFont(new Font(jMenu1.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenu2.setFont(new Font(jMenu2.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenu3.setFont(new Font(jMenu3.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenu4.setFont(new Font(jMenu4.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenu7.setFont(new Font(jMenu7.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuBar1.setFont(new Font(jMenuBar1.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem1.setFont(new Font(jMenuItem1.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem10.setFont(new Font(jMenuItem10.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem11.setFont(new Font(jMenuItem11.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem6.setFont(new Font(jMenuItem6.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem7.setFont(new Font(jMenuItem7.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem8.setFont(new Font(jMenuItem8.getFont().getName(), Font.PLAIN, tamañoLetra));
        jMenuItem9.setFont(new Font(jMenuItem9.getFont().getName(), Font.PLAIN, tamañoLetra));
        
        tabla.setFont(new Font(tabla.getFont().getName(), Font.PLAIN, tamañoLetra));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnGuardarTabla;
    private javax.swing.JButton btnNuevaTarea;
    private javax.swing.JLabel fecha;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel hora;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsignaturas;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCentro;
    private javax.swing.JLabel lblCursos;
    private javax.swing.JLabel lblMaestro;
    private javax.swing.JLabel lblTareasCalificar;
    private javax.swing.JLabel lblTareasCalificar1;
    private javax.swing.JLabel nombreAsignatura;
    private javax.swing.JRadioButton rdbtnc1;
    private javax.swing.JRadioButton rdbtnc2;
    private javax.swing.JRadioButton rdbtnc3;
    private javax.swing.JRadioButton rdbtnc4;
    private javax.swing.JRadioButton rdbtncon1A;
    private javax.swing.JRadioButton rdbtnlen3A;
    private javax.swing.JRadioButton rdbtnmat3A;
    private javax.swing.JRadioButton rdbtnmat3C;
    private javax.swing.JRadioButton rdbtnrel4A;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea txtHagaClic;
    private javax.swing.JTextArea txtHagaClic2;
    private javax.swing.JLabel ventormentaPicture;
    // End of variables declaration//GEN-END:variables

}
