/*
 * Lucia Calzado Piedrabuena
 * Trabajo de Fin de Grado - Grado en Ingenier�a Inform�tica
 * Universidad de Castilla-La Mancha
 */
package appinterface;

import auxiliar.AuxiliarMethods;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JList;
import objects.Alumno;
import controladores.ControladorAlumno;
import controladores.ControladorCompetencia;
import controladores.ControladorPrueba;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashMap;
import objects.Competencia;
import objects.Prueba;

/**
 *
 * @author lucia
 */
public class NuevaPruebaWindow extends javax.swing.JFrame {

    /**
     * Creates new form NuevaTareaWindow
     */
    ControladorAlumno contAlumnos;
    ControladorPrueba contPruebas;
    ControladorCompetencia contCompetencias;
    int asignatura;
    int tamañoLetra;
    boolean presionado;
    DefaultListModel<String> modeloAct = new DefaultListModel<>();
    DefaultListModel<String> modeloAsig = new DefaultListModel<>();
    HashMap<String, Integer> competenciaConID = new HashMap<>(); //nombre competencia, id

    public NuevaPruebaWindow(String strAsignatura, int asignatura, ControladorAlumno contAlumnos, int tamañoLetra) {
        initComponents();
        this.contAlumnos = contAlumnos;
        this.asignatura = asignatura;
        this.tamañoLetra = tamañoLetra;
        contPruebas = new ControladorPrueba();
        contCompetencias = new ControladorCompetencia();
        presionado = false;
        competenciaConID = new HashMap<>();

        //asignamos los modelos de las listas
        listaComAct.setModel(modeloAct);
        listaComAsig.setModel(modeloAsig);

        //para que el panel de descripción se ajuste al texto que contiene
        descripcion.setWrapStyleWord(true);
        descripcion.setLineWrap(true);
        descripcion.setEditable(false);
        
        //ajustamos los paneles que contienen las listas
        jPanel1.setMinimumSize(jPanel1.getSize());
        jPanel2.setMinimumSize(jPanel2.getSize());
        jPanel1.setPreferredSize(new Dimension(300, jPanel1.getPreferredSize().height));
        jPanel2.setPreferredSize(new Dimension(300, jPanel2.getPreferredSize().height));

        //cargamos listas y tabla de alumnos
        cargarCompetencias();
        cargarTabla();
        
        //ajustamos la tabla para que se muestre correctamente al inicio
        tabla.setEnabled(false);
        seleccionarTodaTabla(true);

        try {
            contPruebas.cargarPruebasAsignatura(asignatura);
        } catch (SQLException e) {
            AuxiliarMethods.showWarning(e.toString());
        }

        if (tamañoLetra != 0) {
            cambiarTamañoLetra();
        }

        getDate();

        //Añadir los radio buttons a un grupo
        ButtonGroup cursosGrupo = new ButtonGroup();
        cursosGrupo.add(rdbtnSeleccionar);
        cursosGrupo.add(rdbtnTodos);

        txtAsignatura.setText(strAsignatura);
        //lblImagen1.setIcon(new ImageIcon("assets/plus.png"));
        //lblImagen2.setIcon(new ImageIcon("assets/sheet.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblAsignatura = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        chbxTrabajoAdic = new javax.swing.JCheckBox();
        txtAsignatura = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        rdbtnTodos = new javax.swing.JRadioButton();
        rdbtnSeleccionar = new javax.swing.JRadioButton();
        lblTituloGrande = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        panelTabla = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblTrimestre = new javax.swing.JLabel();
        comboTrimestre = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        txtFecha = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        lblCompetencias = new javax.swing.JLabel();
        lblNombrePrueba = new javax.swing.JLabel();
        lblComActuales = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblComAsig = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextArea();
        btnPasarIzquierda = new javax.swing.JButton();
        btnPasarDerecha = new javax.swing.JButton();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaComAsig = new javax.swing.JList<>();
        lblDatos = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaComAct = new javax.swing.JList<>();
        lblNombreCompetencia = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva tarea");
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(btnCancelar, gridBagConstraints);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(btnGuardar, gridBagConstraints);

        lblAsignatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAsignatura.setText("Asignatura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblAsignatura, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitulo.setText("Título:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblTitulo, gridBagConstraints);

        lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeso.setText("Peso (%):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblPeso, gridBagConstraints);

        chbxTrabajoAdic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbxTrabajoAdic.setText("Trabajo adicional");
        chbxTrabajoAdic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxTrabajoAdicActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(chbxTrabajoAdic, gridBagConstraints);

        txtAsignatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAsignatura.setEnabled(false);
        txtAsignatura.setMaximumSize(new java.awt.Dimension(100, 22));
        txtAsignatura.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(txtAsignatura, gridBagConstraints);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo.setMinimumSize(new java.awt.Dimension(100, 22));
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtTitulo, gridBagConstraints);

        rdbtnTodos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbtnTodos.setSelected(true);
        rdbtnTodos.setText("Para todos los alumnos");
        rdbtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnTodosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        getContentPane().add(rdbtnTodos, gridBagConstraints);

        rdbtnSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbtnSeleccionar.setText("Seleccionar alumnos");
        rdbtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSeleccionarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(rdbtnSeleccionar, gridBagConstraints);

        lblTituloGrande.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloGrande.setText("Crear una nueva tarea o prueba");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblTituloGrande, gridBagConstraints);

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(txtPeso, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 27;
        getContentPane().add(filler6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 35;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 36;
        gridBagConstraints.gridwidth = 20;
        getContentPane().add(filler10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 10;
        getContentPane().add(filler12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(filler13, gridBagConstraints);

        panelTabla.setMinimumSize(new java.awt.Dimension(300, 200));
        panelTabla.setLayout(new javax.swing.BoxLayout(panelTabla, javax.swing.BoxLayout.LINE_AXIS));

        tabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos", "Nombre", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
        }

        panelTabla.add(jScrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 11;
        getContentPane().add(panelTabla, gridBagConstraints);

        lblTrimestre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrimestre.setText("Trimestre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblTrimestre, gridBagConstraints);

        comboTrimestre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboTrimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º", "2º", "3º" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(comboTrimestre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(filler3, gridBagConstraints);

        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha.setMinimumSize(new java.awt.Dimension(100, 22));
        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaFocusLost(evt);
            }
        });
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(txtFecha, gridBagConstraints);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblFecha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        getContentPane().add(filler15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 16;
        getContentPane().add(filler11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 9;
        getContentPane().add(filler16, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridheight = 6;
        getContentPane().add(filler9, gridBagConstraints);

        lblCompetencias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCompetencias.setText("Competencias de");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblCompetencias, gridBagConstraints);

        lblNombrePrueba.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblNombrePrueba, gridBagConstraints);

        lblComActuales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComActuales.setText("Competencias actuales:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(lblComActuales, gridBagConstraints);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblDescripcion, gridBagConstraints);

        lblComAsig.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComAsig.setText("Competencias de la asignatura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 18;
        getContentPane().add(lblComAsig, gridBagConstraints);

        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcion.setRows(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(descripcion, gridBagConstraints);

        btnPasarIzquierda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPasarIzquierda.setText("<<");
        btnPasarIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarIzquierdaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        getContentPane().add(btnPasarIzquierda, gridBagConstraints);

        btnPasarDerecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPasarDerecha.setText(">>");
        btnPasarDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarDerechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 20;
        getContentPane().add(btnPasarDerecha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler18, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.gridwidth = 17;
        getContentPane().add(filler19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 16;
        getContentPane().add(filler20, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 15;
        getContentPane().add(filler21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 17;
        getContentPane().add(filler24, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 34;
        getContentPane().add(filler23, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 37;
        getContentPane().add(filler25, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 31;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler26, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 33;
        getContentPane().add(filler27, gridBagConstraints);

        listaComAsig.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listaComAsig.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaComAsigMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaComAsig);

        jPanel1.add(jScrollPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        lblDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDatos.setText("Datos principales:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(lblDatos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 17;
        getContentPane().add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 10;
        getContentPane().add(filler4, gridBagConstraints);

        listaComAct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listaComAct.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaComActMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listaComAct);

        jPanel2.add(jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 7;
        getContentPane().add(jPanel2, gridBagConstraints);

        lblNombreCompetencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(lblNombreCompetencia, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 19;
        getContentPane().add(filler7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(filler8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 31;
        getContentPane().add(filler5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rdbtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSeleccionarActionPerformed
        tabla.setEnabled(true);
        seleccionarTodaTabla(false);
    }//GEN-LAST:event_rdbtnSeleccionarActionPerformed
    
    private void cargarTabla(){
        DefaultTableModel model = (DefaultTableModel) tabla.getModel(); //modelo para introducir filas en la tabla
        if (model.getRowCount() == 0) {
            model.setRowCount(0);

            //Rellenar tabla
            Object[] row = new Object[3];

            //TODO esto solo se rellena si se le da al botón cargar tabla
            for (Alumno alumno : contAlumnos.getAlumnosAsignatura().get(asignatura)) {
                row[0] = alumno.getNombre();
                row[1] = alumno.getApellidos();
                model.addRow(row);
            }
        }
    }
    private void rdbtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnTodosActionPerformed
        tabla.setEnabled(false);
        seleccionarTodaTabla(true);
    }//GEN-LAST:event_rdbtnTodosActionPerformed

    private void chbxTrabajoAdicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxTrabajoAdicActionPerformed
        txtPeso.setEnabled(!chbxTrabajoAdic.isSelected());
    }//GEN-LAST:event_chbxTrabajoAdicActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtPeso.getText().equals("") || chbxTrabajoAdic.isSelected()) {
            int peso = !chbxTrabajoAdic.isSelected() ? Integer.parseInt(String.valueOf(txtPeso.getText().charAt(0))) : 0;
            int trimestre = Integer.parseInt(String.valueOf(comboTrimestre.getSelectedItem().toString().charAt(0)));
            //validamos que la fecha tiene el formato correcto

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            dateFormat.setLenient(false);

            try {
                dateFormat.parse(txtFecha.getText().trim());
                Prueba p = new Prueba(asignatura, txtTitulo.getText(), txtFecha.getText(), trimestre, peso, recogerCompetencias());
                //hacer commit también en competenciasPorPrueba y guardar eso en algun sitio --> controladorPrueba.competenciasPrueba

                contPruebas.añadirPruebaAAsignatura(p, asignatura);
                try {
                    p.setIdPrueba(p.commitNuevaPrueba());
                    p.commitCompetencias();
                } catch (SQLException e){
                    AuxiliarMethods.showWarning("No se ha podido introducir la prueba en la base de datos.\nMás detalles: "+e.toString());
        
                }

                this.dispose();
            } catch (ParseException pe) {
                AuxiliarMethods.showWarning("Introduzca una fecha válida.\nFormato: dd/mm/aaaa");
            }

        } else {
            AuxiliarMethods.showWarning("Si la prueba no tiene peso, seleccione Trabajo adicional.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMousePressed
        // TODO add your handling code here:
        if (!presionado) {
            txtFecha.setText("");
            presionado = true;
        }
    }//GEN-LAST:event_txtFechaMousePressed

    private void txtFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusLost
        // TODO add your handling code here:
        if (txtFecha.getText().equals("")) {
            getDate();
        }
    }//GEN-LAST:event_txtFechaFocusLost

    private void listaComActMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComActMousePressed
        listaComAct = (JList) evt.getSource();

        for (Competencia c1 : contCompetencias.getCompetenciasAsignatura().get(asignatura)) {
            if (c1.getIdCompetencia() == competenciaConID.get(modeloAct.get(listaComAct.getSelectedIndex()))) {
                descripcion.setText(c1.getDescripcion());
            }
        }
    }//GEN-LAST:event_listaComActMousePressed

    private void listaComAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComAsigMouseClicked
        listaComAsig = (JList) evt.getSource();

        for (Competencia c1 : contCompetencias.getCompetenciasAsignatura().get(asignatura)) {
            //System.out.println(modeloAsig.get(listaComAsig.getSelectedIndex()));
            if (c1.getIdCompetencia() == competenciaConID.get(modeloAsig.get(listaComAsig.getSelectedIndex()))) {
                descripcion.setText(c1.getDescripcion());
                lblNombreCompetencia.setText(c1.getNombre());
            }
        }
    }//GEN-LAST:event_listaComAsigMouseClicked

    private void btnPasarDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarDerechaActionPerformed
        if (listaComAsig.getSelectedIndex() != -1) {
            for (Competencia c1 : contCompetencias.getCompetenciasAsignatura().get(asignatura)) {
                if (c1.getIdCompetencia() == competenciaConID.get(modeloAsig.get(listaComAsig.getSelectedIndex()))) {
                    descripcion.setText(c1.getDescripcion());
                }
            }
            modeloAct.addElement(modeloAsig.get(listaComAsig.getSelectedIndex())); //ponemos lo que hay seleccionado en una lista, en la otra
            modeloAsig.remove(listaComAsig.getSelectedIndex()); //y borramos el elemento de la lista, lo "movemos"
        }
    }//GEN-LAST:event_btnPasarDerechaActionPerformed

    private void btnPasarIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarIzquierdaActionPerformed
        if (listaComAct.getSelectedIndex() != -1) {
            for (Competencia c1 : contCompetencias.getCompetenciasAsignatura().get(asignatura)) {
                if (c1.getIdCompetencia() == competenciaConID.get(modeloAct.get(listaComAct.getSelectedIndex()))) {
                    descripcion.setText(c1.getDescripcion());                 
                }
            }
            modeloAsig.addElement(modeloAct.get(listaComAct.getSelectedIndex()));
            modeloAct.remove(listaComAct.getSelectedIndex());
        }
    }//GEN-LAST:event_btnPasarIzquierdaActionPerformed

    private void txtTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyReleased
        lblNombrePrueba.setText(txtTitulo.getText());
    }//GEN-LAST:event_txtTituloKeyReleased

    private void getDate() {
        //Rellenamos el campo de fecha por defecto con la fecha de hoy para que sepan el formato
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        txtFecha.setText(formatter.format(date));
    }

    private void cargarCompetencias() {
        try {
            contCompetencias.cargarCompetenciasAsignatura(asignatura);
        } catch (SQLException e) {
            System.out.println(e.toString());
        }

        for (int i = 0; i < contCompetencias.getCompetenciasAsignatura().get(asignatura).size(); i++) {
            modeloAsig.addElement(contCompetencias.getCompetenciasAsignatura().get(asignatura).get(i).getNombre());
            competenciaConID.put(contCompetencias.getCompetenciasAsignatura().get(asignatura).get(i).getNombre(), contCompetencias.getCompetenciasAsignatura().get(asignatura).get(i).getIdCompetencia());
        }
    }
    
    private void seleccionarTodaTabla(boolean seleccionar){
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        for (int i=0; i<tabla.getRowCount(); i++){
            model.setValueAt(seleccionar, i, 2);
        }
    }
    
    public ArrayList recogerCompetencias(){
        ArrayList<Integer> listaCompetencias = new ArrayList<>();
        for (int i=0; i<modeloAct.getSize(); i++){
            listaCompetencias.add(competenciaConID.get(modeloAct.get(i)));
        }
        return listaCompetencias;
    }

    private void cambiarTamañoLetra() {
        lblAsignatura.setFont(new Font(lblAsignatura.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblCompetencias.setFont(new Font(lblCompetencias.getFont().getName(), Font.PLAIN, tamañoLetra + lblCompetencias.getFont().getSize()));
        lblDescripcion.setFont(new Font(lblDescripcion.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblComAsig.setFont(new Font(lblComAsig.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblComActuales.setFont(new Font(lblComActuales.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblFecha.setFont(new Font(lblFecha.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblPeso.setFont(new Font(lblPeso.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblTitulo.setFont(new Font(lblTitulo.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblTrimestre.setFont(new Font(lblTrimestre.getFont().getName(), Font.PLAIN, tamañoLetra));
        lblNombreCompetencia.setFont(new Font(lblNombreCompetencia.getFont().getName(), Font.BOLD, tamañoLetra));
        lblNombrePrueba.setFont(new Font(lblNombrePrueba.getFont().getName(), Font.PLAIN, tamañoLetra + lblNombrePrueba.getFont().getSize()));
        lblTituloGrande.setFont(new Font(lblTituloGrande.getFont().getName(), Font.PLAIN, tamañoLetra + lblTituloGrande.getFont().getSize()));
        lblDatos.setFont(new Font(lblDatos.getFont().getName(), Font.PLAIN, tamañoLetra + lblDatos.getFont().getSize()));

        txtAsignatura.setFont(new Font(txtAsignatura.getFont().getName(), Font.PLAIN, tamañoLetra));
        txtFecha.setFont(new Font(txtFecha.getFont().getName(), Font.PLAIN, tamañoLetra));
        txtPeso.setFont(new Font(txtPeso.getFont().getName(), Font.PLAIN, tamañoLetra));
        txtTitulo.setFont(new Font(txtTitulo.getFont().getName(), Font.PLAIN, tamañoLetra));
        descripcion.setFont(new Font(descripcion.getFont().getName(), Font.PLAIN, tamañoLetra));

        btnCancelar.setFont(new Font(btnCancelar.getFont().getName(), Font.PLAIN, tamañoLetra));
        btnGuardar.setFont(new Font(btnGuardar.getFont().getName(), Font.PLAIN, tamañoLetra));

        rdbtnSeleccionar.setFont(new Font(rdbtnSeleccionar.getFont().getName(), Font.PLAIN, tamañoLetra));
        rdbtnTodos.setFont(new Font(rdbtnTodos.getFont().getName(), Font.PLAIN, tamañoLetra));

        chbxTrabajoAdic.setFont(new Font(rdbtnSeleccionar.getFont().getName(), Font.PLAIN, tamañoLetra));

        tabla.setFont(new Font(tabla.getFont().getName(), Font.PLAIN, tamañoLetra));

        comboTrimestre.setFont(new Font(comboTrimestre.getFont().getName(), Font.PLAIN, tamañoLetra));

        listaComAct.setFont(new Font(listaComAct.getFont().getName(), Font.PLAIN, tamañoLetra));
        listaComAsig.setFont(new Font(listaComAsig.getFont().getName(), Font.PLAIN, tamañoLetra));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPasarDerecha;
    private javax.swing.JButton btnPasarIzquierda;
    private javax.swing.JCheckBox chbxTrabajoAdic;
    private javax.swing.JComboBox<String> comboTrimestre;
    private javax.swing.JTextArea descripcion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblComActuales;
    private javax.swing.JLabel lblComAsig;
    private javax.swing.JLabel lblCompetencias;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombreCompetencia;
    private javax.swing.JLabel lblNombrePrueba;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloGrande;
    private javax.swing.JLabel lblTrimestre;
    private javax.swing.JList<String> listaComAct;
    private javax.swing.JList<String> listaComAsig;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JRadioButton rdbtnSeleccionar;
    private javax.swing.JRadioButton rdbtnTodos;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
