/*
 * Lucia Calzado Piedrabuena
 * Trabajo de Fin de Grado - Grado en Ingenier�a Inform�tica
 * Universidad de Castilla-La Mancha
 */
package appsmallinterfaces;

import auxiliar.AuxiliarMethods;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.ImageIcon;
import objects.Opciones;

/**
 *
 * @author lucia
 */
public class Ayuda extends javax.swing.JFrame {

    Opciones opciones;
    
    
    public Ayuda(Opciones opciones, int tabSeleccionada) {
        this.opciones = opciones;
        initComponents();
        jTabbedPane1.setSelectedIndex(tabSeleccionada);
        ejecutarOpciones();
    }
    
    /**
     * Ejecución del look and feel elegido en el login
     */
     private void ejecutarOpciones() {
        List<Component> components = AuxiliarMethods.getAllComponents(this);

        for (Component c : components) {
            c.setFont(new Font(c.getFont().getName(), c.getFont().getStyle(), opciones.getTamañoLetra()));
            if (opciones.getOscuro()) {
                c.setForeground(Color.LIGHT_GRAY);
            }
        }

        lblTitulo1.setFont(new Font(lblTitulo1.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo2.setFont(new Font(lblTitulo2.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo3.setFont(new Font(lblTitulo3.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo4.setFont(new Font(lblTitulo4.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo5.setFont(new Font(lblTitulo5.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo6.setFont(new Font(lblTitulo6.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo7.setFont(new Font(lblTitulo7.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo8.setFont(new Font(lblTitulo8.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo9.setFont(new Font(lblTitulo9.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));
        lblTitulo11.setFont(new Font(lblTitulo11.getFont().getName(), Font.BOLD, opciones.getTamañoLetra() + 15));

        //cambiamos el color de fondo de todos los containers del frame
        Color colorBackground = opciones.getColorBackground();
        this.getContentPane().setBackground(colorBackground);
        panel1.setBackground(colorBackground);
        panel2.setBackground(colorBackground);
        panel3.setBackground(colorBackground);
        panel4.setBackground(colorBackground);
        panel5.setBackground(colorBackground);
        panel6.setBackground(colorBackground);
        panel7.setBackground(colorBackground);
        panel8.setBackground(colorBackground);
        panel9.setBackground(colorBackground);
        panel11.setBackground(colorBackground);
        
        txt1.setBackground(colorBackground);
        txt2.setBackground(colorBackground);
        txt3.setBackground(colorBackground);
        txt4.setBackground(colorBackground);
        txt5.setBackground(colorBackground);
        txt6.setBackground(colorBackground);
        txt7.setBackground(colorBackground);
        txt8.setBackground(colorBackground);
        txt9.setBackground(colorBackground);
        txt11.setBackground(colorBackground);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel2 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextPane();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel3 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txt3 = new javax.swing.JTextPane();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel4 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txt4 = new javax.swing.JTextPane();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel5 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txt5 = new javax.swing.JTextPane();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel6 = new javax.swing.JPanel();
        lblTitulo6 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txt6 = new javax.swing.JTextPane();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel7 = new javax.swing.JPanel();
        lblTitulo7 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txt7 = new javax.swing.JTextPane();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel8 = new javax.swing.JPanel();
        lblTitulo8 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        txt8 = new javax.swing.JTextPane();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel9 = new javax.swing.JPanel();
        lblTitulo9 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        txt9 = new javax.swing.JTextPane();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel10 = new javax.swing.JPanel();
        lblTitulo10 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        txt10 = new javax.swing.JTextPane();
        filler31 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler33 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        panel11 = new javax.swing.JPanel();
        lblTitulo11 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txt11 = new javax.swing.JTextPane();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manual de ayuda");
        setBounds(new java.awt.Rectangle(250, 100, 0, 0));
        setIconImage(new ImageIcon("assets/logo.png").getImage());
        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(1500, 700));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panel1.setLayout(new java.awt.BorderLayout());

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo1.setText("     Introducción");
        panel1.add(lblTitulo1, java.awt.BorderLayout.PAGE_START);

        txt1.setEditable(false);
        txt1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt1.setText("Bienvenido/a a esta aplicación para gestionar y almacenar las pruebas y las notas de sus alumnos.\n\nPuede navegar por los temas de ayuda en la izquierda para obtener más información sobre cada uno.\n\nEsta ayuda se puede acceder desde cualquier ventana, pulsando en el menú Ayuda -> Manual de ayuda.");
        jScrollPane1.setViewportView(txt1);

        panel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        panel1.add(filler1, java.awt.BorderLayout.LINE_START);
        panel1.add(filler2, java.awt.BorderLayout.PAGE_END);
        panel1.add(filler3, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Introducción", panel1);

        panel2.setLayout(new java.awt.BorderLayout());

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo2.setText("     Ventana principal");
        panel2.add(lblTitulo2, java.awt.BorderLayout.PAGE_START);

        txt2.setEditable(false);
        txt2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt2.setText("Esta es la ventana a la que se accede al iniciar sesión.\n\nSeleccione un curso y una asignatura para cargar los datos del alumnado.\n\nCARACTERÍSTICAS PRINCIPALES:\n- Cuenta con una tabla en la que se pueden visualizar las notas finales de los alumnos para cada trimestre, junto con una media tanto por alumno como por trimestre, y la nota final de la asignatura.\n- Debajo de la tabla, están las estadísticas del curso. Estas se pueden ver gráficamente haciendo clic en el botón del gráfico.\n- Puede ver las fechas límite para poner las notas finales pasando el ratón por encima de los nombres de los trimestres.\n\nNAVEGACIÓN:\nDesde esta ventana se puede navegar a todas las funcionalidades del programa:\n- Crear una tarea o prueba nueva en el botón \"Crear tarea o prueba\".\n- Calificar tareas o pruebas ya existentes en el botón \"Calificar tareas o pruebas\".\n- Obtener un informe personal del alumnado de la asignatura haciendo clic en el nombre del/de la alumno/a en cuestión en la tabla.\n- Obtener un informe general trimestral haciendo clic en el trimestre correspondiente, en la cabecera de la tabla.\n- Cambiar los datos del/la maestro/a en el botón \"Editar usuario\".\n- Añadir un alumno nuevo a la asignatura en el botón \"Añadir alumno\".");
        jScrollPane10.setViewportView(txt2);

        panel2.add(jScrollPane10, java.awt.BorderLayout.CENTER);
        panel2.add(filler4, java.awt.BorderLayout.LINE_START);
        panel2.add(filler5, java.awt.BorderLayout.PAGE_END);
        panel2.add(filler6, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Ventana principal", panel2);

        panel3.setLayout(new java.awt.BorderLayout());

        lblTitulo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo3.setText("     Crear tarea o prueba");
        panel3.add(lblTitulo3, java.awt.BorderLayout.PAGE_START);

        txt3.setEditable(false);
        txt3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt3.setText("En esta ventana se pueden crear pruebas, exámenes o tareas (a partir de ahora, \"pruebas\") nuevas y asignarlas al alumnado.\n\nPara ello, rellene el formulario que se detalla a continuación:\nDATOS PRINCIPALES:\n- Título: el título o nombre de la pueba. \n- Peso: el peso de la prueba dentro de la asignatura. Por ejemplo, si se elige peso 5, querrá decir que esta prueba supondrá un 50% de la nota final del alumnado en la asignatura. Si es una recuperación o un trabajo adicional que no tiene peso en la nota final, se debe seleccionar \"Recuperación\".\n- Trimestre: el trimestre en el que se lleva a cabo la prueba.\n- Fecha: la fecha en la que se realizará la prueba.\n- Etiqueta: una forma más corta de designar a la prueba. Tiene, como máximo, una longitud de 5 caracteres.\n\nCOMPETENCIAS: \n- Lista de competencias: seleccione las competencias que desee añadir a la prueba. Prresione Ctrl izquierdo mientras hace clic para seleccionar varias.\n- Descripción: la descripción de cada competencia aparecerá aquí al seleccionarla en la lista.\n\nALUMNOS:\nPuede elegir los/las alumnos/as a los/las que asignar determinadas pruebas. Si la prueba la realizarán todos los alumnos, seleccione \"Todo el alumnado\". Si no es así, seleccione \"Seleccionar alumnos/as\", y la tabla que hay debajo se activará. Seleccione los/las alumnos/as para los/las que quiere asignar una nota a la prueba.\n\nCuando haya terminado, guarde la prueba mediante el botón \"Guardar\". \nPuede cancelar todo este proceso pulsando el botón \"Cancelar\".");
        jScrollPane11.setViewportView(txt3);

        panel3.add(jScrollPane11, java.awt.BorderLayout.CENTER);
        panel3.add(filler7, java.awt.BorderLayout.LINE_START);
        panel3.add(filler8, java.awt.BorderLayout.PAGE_END);
        panel3.add(filler9, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Crear tarea o prueba", panel3);

        panel4.setLayout(new java.awt.BorderLayout());

        lblTitulo4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo4.setText("     Calificar tarea o prueba");
        panel4.add(lblTitulo4, java.awt.BorderLayout.PAGE_START);

        txt4.setEditable(false);
        txt4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt4.setText("En esta ventana puede calificar las pruebas que ha creado para su alumnado.\n\nSeleccione el trimestre y prueba que quiere calificar.\n\nPuede asignar una nota y un comentario a cada nota del alumnado. Los/las alumnos/as que no tengan que realizar esta prueba tendrán, por defecto, un guión (-) en la nota y un comentario diciendo \"No tiene que realizar la prueba\".\n\nA la derecha tiene un panel de estadísticas. Puede presionar el botón \"Refrescar estadísticas\" para refrescar la media de alumnos aprobados en la prueba, según haya introducido los datos en la tabla.\n\nPara guardar, pulse el botón \"Guardar\".\nPara salir sin guardar los cambios, pulse el botón \"Cancelar\" o cierre la ventana.\n\n");
        jScrollPane12.setViewportView(txt4);

        panel4.add(jScrollPane12, java.awt.BorderLayout.CENTER);
        panel4.add(filler10, java.awt.BorderLayout.LINE_START);
        panel4.add(filler11, java.awt.BorderLayout.PAGE_END);
        panel4.add(filler12, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Calificar tareas o pruebas", panel4);

        panel5.setLayout(new java.awt.BorderLayout());

        lblTitulo5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo5.setText("     Borrar tarea o prueba");
        panel5.add(lblTitulo5, java.awt.BorderLayout.PAGE_START);

        txt5.setEditable(false);
        txt5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt5.setText("Para saber cómo borrar una prueba, haga clic en \"Informe del trimestre\".");
        jScrollPane13.setViewportView(txt5);

        panel5.add(jScrollPane13, java.awt.BorderLayout.CENTER);
        panel5.add(filler13, java.awt.BorderLayout.LINE_START);
        panel5.add(filler14, java.awt.BorderLayout.PAGE_END);
        panel5.add(filler15, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Borrar tarea o prueba", panel5);

        panel6.setLayout(new java.awt.BorderLayout());

        lblTitulo6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo6.setText("     Informe del alumnado");
        panel6.add(lblTitulo6, java.awt.BorderLayout.PAGE_START);

        txt6.setEditable(false);
        txt6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt6.setText("Esta ventana muestra un informe personal de las notas de las pruebas y de las notas finales de cada trimestre de un/a alumno/a en particular. Se puede acceder a esta vista haciendo clic en el nombre de un/a alumno/a en la tabla de la ventana principal.\n\nSe pueden distinguir cuatro secciones: notas del primer trimestre, notas del segundo trimestre, notas del tercer trimestre, comentario y notas finales.\n\nEn las tablas que hay arriba se muestran las notas de las pruebas, organizadas por trimestres, la nota media de las pruebas que están calificadas y la nota final del/la alumno/a en ese trimestre, así como su calificación (Insuficiente, suficiente, bien, notable o sobresaliente).\nSi deja el ratón encima de una nota, puede ver el comentario asociado a esa nota.\nTambién puede ver su trayectoria prestando atención a las flechas o los guiones que aparecen a la derecha de la nota media.\n- Si es una flecha verde hacia arriba, el/la alumno/a ha mejorado la nota media.\n- Si es una fecha roja hacia abajo, el/la alumno/a ha empeorado la nota media.\n- Si es un guión, el alumno ha mantenido la nota dentro de un margen.\n\nPuede asignarle un comentario general por asignatura a cada alumno/a en el campo de texto \"Comentarios\".\n\nPor último, en el centro de la ventana, está la nota media de los tres trimestres y la nota final de la asignatura.\n\nPara guardar los cambios, pulse el botón \"Guardar\".\nPara cancelar los cambios y salir sin guardar, pulse el botón \"Cancelar\" o cierre la ventana.");
        jScrollPane14.setViewportView(txt6);

        panel6.add(jScrollPane14, java.awt.BorderLayout.CENTER);
        panel6.add(filler16, java.awt.BorderLayout.LINE_START);
        panel6.add(filler17, java.awt.BorderLayout.PAGE_END);
        panel6.add(filler18, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Informe del alumnado", panel6);

        panel7.setLayout(new java.awt.BorderLayout());

        lblTitulo7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo7.setText("     Informe del trimestre");
        panel7.add(lblTitulo7, java.awt.BorderLayout.PAGE_START);

        txt7.setEditable(false);
        txt7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt7.setText("En esta ventana puede ver un informe general por trimestres. Para acceder a ella, pulse el nombre del trimestre en la ventana principal.\n\nEsta ventana se divide en dos vistas.\nNOTAS:\nAquí puede encontrar una tabla con todas las pruebas del trimestre, así como la nota de cada alumno/a para cada una de ellas. Esta ventana es solo para consulta. Si desea calificar a los alumnos o modificar una calificación, haga clic en el botón \"Calificar tareas o pruebas\".\nLos alumnos que no tienen que realizar una prueba, tendrán un guión (-) en la casilla de su nota.\n\nPRUEBAS:\nAquí puede modificar el título, fecha, etiqueta y/o peso de las pruebas creadas, así como borrar una prueba. Tenga en cuenta que borrar una prueba borrará tanto la prueba como todas las notas asociadas a los alumnos que la hicieron.\nTambién puede volver a visualizar las competencias, pero no puede modificarlas. Si desea modificar las competencias, deberá borrar la prueba y crear una nueva.\n\nPuede salir de esta ventana cerrándola o presionando el botón \"Atrás\".");
        jScrollPane15.setViewportView(txt7);

        panel7.add(jScrollPane15, java.awt.BorderLayout.CENTER);
        panel7.add(filler19, java.awt.BorderLayout.LINE_START);
        panel7.add(filler20, java.awt.BorderLayout.PAGE_END);
        panel7.add(filler21, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Informe del trimestre", panel7);

        panel8.setLayout(new java.awt.BorderLayout());

        lblTitulo8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo8.setText("     Añadir alumn@s");
        panel8.add(lblTitulo8, java.awt.BorderLayout.PAGE_START);

        txt8.setEditable(false);
        txt8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt8.setText("Tiene dos opciones para añadir alumnos/as que se incorporen a mitad del curso a cualquier asignatura :\n\nUN ALUMNO:\n- Añadir un/a solo/a alumno/a mediante el botón \"Añadir alumno/a\" en la ventana principal.\n\nRellene el formulario con los datos personales del/de la alumno/a según se muestran.\n\nPulse el botón \"Guardar\" para guardar los cambios.\nPulse el botón \"Cancelar\" o cierre la ventana para salir sin guardar los cambios.\n\n\nVARIOS ALUMNOS:\n- Añadir varios/as alumnos/as cargando un Excel con sus datos mediante el menú Editar > Alumnado > Añadir alumnos/as...\n\nEste Excel debe rellenarse con los datos personales del/de la alumno/a de la siguiente manera:\nPrimera columna: nombre\nSegunda columna: apellido/s\nTercera columna: DNI\nCuarta columna: fecha de nacimiento\n\nUna vez haya cargado correctamente los/las alumnos/as, aparecerán en la asignatura elegida.");
        jScrollPane16.setViewportView(txt8);

        panel8.add(jScrollPane16, java.awt.BorderLayout.CENTER);
        panel8.add(filler22, java.awt.BorderLayout.LINE_START);
        panel8.add(filler23, java.awt.BorderLayout.PAGE_END);
        panel8.add(filler24, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Añadir alumn@s", panel8);

        panel9.setLayout(new java.awt.BorderLayout());

        lblTitulo9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo9.setText("     Editar datos personales");
        panel9.add(lblTitulo9, java.awt.BorderLayout.PAGE_START);

        txt9.setEditable(false);
        txt9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt9.setText("Puede editar algunos de sus datos que se muestran en la aplicación presionando el botón \"Editar usuario\" en la ventana principal.\n\nPuede cambiar:\n- La imagen que se muestra en la ventana principal.\n- El nombre que se muestra en la ventana principal.\n- Su contraseña de inicio de sesión.\n\nPulse \"Guardar\" para guardar los cambios.\nPulse \"Cancelar\" o cierre la ventana para salir sin guardar los cambios.");
        jScrollPane17.setViewportView(txt9);

        panel9.add(jScrollPane17, java.awt.BorderLayout.CENTER);
        panel9.add(filler25, java.awt.BorderLayout.LINE_START);
        panel9.add(filler26, java.awt.BorderLayout.PAGE_END);
        panel9.add(filler27, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Editar datos personales", panel9);

        panel10.setLayout(new java.awt.BorderLayout());

        lblTitulo10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo10.setText("     Personalización y temas");
        panel10.add(lblTitulo10, java.awt.BorderLayout.PAGE_START);

        txt10.setEditable(false);
        txt10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt10.setText("Puede personalizar la apariencia de la aplicación presionando el botón de la rueda de opciones en la ventana de inicio de sesión.\n\nLas opciones de personalización son las siguientes:\n- Tamaño de la letra.\n- Color de las notas aprobadas (>=5).\n- Color de las notas suspensas (<5).\n- Color del fondo.\n\nTambién cuenta con un tema oscuro, que se activa al seleccionar la casilla \"Modo oscuro\".\nAlternativamente, puede usar el \"Modo daltónicos\", que elige por defecto colores fáciles de distinguir para las personas con daltonismo para las notas aprobadas y suspensas.\n\nPara aplicar las elecciones de personalización, presione el botón \"Aplicar\".");
        jScrollPane19.setViewportView(txt10);

        panel10.add(jScrollPane19, java.awt.BorderLayout.CENTER);
        panel10.add(filler31, java.awt.BorderLayout.LINE_START);
        panel10.add(filler32, java.awt.BorderLayout.PAGE_END);
        panel10.add(filler33, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Personalización y temas", panel10);

        panel11.setLayout(new java.awt.BorderLayout());

        lblTitulo11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo11.setText("     Fallos y errores");
        panel11.add(lblTitulo11, java.awt.BorderLayout.PAGE_START);

        txt11.setEditable(false);
        txt11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt11.setText("Por favor, si encuentra algún fallo o error en la aplicación, diríjase a un administrador o escriba a lucia.calzado1@alu.uclm.es.");
        jScrollPane18.setViewportView(txt11);

        panel11.add(jScrollPane18, java.awt.BorderLayout.CENTER);
        panel11.add(filler28, java.awt.BorderLayout.LINE_START);
        panel11.add(filler29, java.awt.BorderLayout.PAGE_END);
        panel11.add(filler30, java.awt.BorderLayout.LINE_END);

        jTabbedPane1.addTab("Fallos y errores", panel11);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler33;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo10;
    private javax.swing.JLabel lblTitulo11;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JLabel lblTitulo7;
    private javax.swing.JLabel lblTitulo8;
    private javax.swing.JLabel lblTitulo9;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel10;
    private javax.swing.JPanel panel11;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel8;
    private javax.swing.JPanel panel9;
    private javax.swing.JTextPane txt1;
    private javax.swing.JTextPane txt10;
    private javax.swing.JTextPane txt11;
    private javax.swing.JTextPane txt2;
    private javax.swing.JTextPane txt3;
    private javax.swing.JTextPane txt4;
    private javax.swing.JTextPane txt5;
    private javax.swing.JTextPane txt6;
    private javax.swing.JTextPane txt7;
    private javax.swing.JTextPane txt8;
    private javax.swing.JTextPane txt9;
    // End of variables declaration//GEN-END:variables
}
