/*
 * Lucia Calzado Piedrabuena
 * Trabajo de Fin de Grado - Grado en Ingenier�a Inform�tica
 * Universidad de Castilla-La Mancha
 */
package appsmallinterfaces;

import auxiliar.AuxiliarMethods;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import objects.Competencia;
import controladores.ControladorCompetencia;
import controladores.ControladorPrueba;

/**
 *
 * @author lucia
 */
public class EditarCompetenciasWindow extends javax.swing.JFrame {

    ControladorCompetencia contCompetencias;
    ControladorPrueba contPruebas;
    DefaultListModel<String> modeloAct = new DefaultListModel<>();
    DefaultListModel<String> modeloAsig = new DefaultListModel<>();
    HashMap<String, Integer> competenciaConID = new HashMap<String, Integer>(); //nombre competencia, id
    int asignatura;

    /**
     * Crea un form
     *
     * @param contCompetencias
     * @param contPrueba
     * @param nombrePrueba
     * @param asignatura
     */
    public EditarCompetenciasWindow(ControladorCompetencia contCompetencias, ControladorPrueba contPrueba, String nombrePrueba, int asignatura) {
        initComponents();
        this.asignatura = asignatura;
        this.contPruebas = contPrueba;
        this.contCompetencias = contCompetencias;
        competenciaConID = new HashMap<>();

        lblAyuda.setEditable(false);
        descripcion.setEditable(false);
        listaComAct.setModel(modeloAct);
        listaComAsig.setModel(modeloAsig);
        
        descripcion.setWrapStyleWord(true);
        descripcion.setLineWrap(true);
        lblAyuda.setWrapStyleWord(true);
        lblAyuda.setLineWrap(true);

        lblNombrePrueba.setText(nombrePrueba);

        cargarCompetencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComAct = new javax.swing.JList<>();
        lblComActuales = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        btnGuardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaComAsig = new javax.swing.JList<>();
        lblComAsig = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        lblAyuda = new javax.swing.JTextArea();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        lblNuevaPrueba = new javax.swing.JLabel();
        lblNombrePrueba = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Competencias de la prueba");
        setBounds(new java.awt.Rectangle(600, 200, 0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblDescripcion.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(lblDescripcion, gridBagConstraints);

        listaComAct.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaComActMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listaComAct);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        lblComActuales.setText("Competencias actuales:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(lblComActuales, gridBagConstraints);

        descripcion.setBackground(getBackground());
        descripcion.setColumns(20);
        descripcion.setRows(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(descripcion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 12;
        getContentPane().add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        getContentPane().add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        getContentPane().add(filler6, gridBagConstraints);

        btnGuardar.setText("Cargar");
        btnGuardar.setToolTipText("");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(btnGuardar, gridBagConstraints);

        listaComAsig.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaComAsigMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaComAsig);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 4;
        getContentPane().add(jScrollPane3, gridBagConstraints);

        lblComAsig.setText("Competencias de la asignatura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        getContentPane().add(lblComAsig, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler7, gridBagConstraints);

        lblAyuda.setBackground(getBackground());
        lblAyuda.setColumns(20);
        lblAyuda.setRows(5);
        lblAyuda.setText("Doble clic en cualquier tabla para mover las competencias.");
        lblAyuda.setPreferredSize(new java.awt.Dimension(100, 84));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        getContentPane().add(lblAyuda, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        getContentPane().add(filler8, gridBagConstraints);

        lblNuevaPrueba.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNuevaPrueba.setText("Competencias de");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblNuevaPrueba, gridBagConstraints);

        lblNombrePrueba.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblNombrePrueba.setText("@nombrePrueba");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblNombrePrueba, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(filler9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(filler10, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaComAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComAsigMouseClicked
        listaComAsig = (JList) evt.getSource();
        int index = 0;

        for (Competencia c1 : contCompetencias.getCompetenciasAsignatura().get(asignatura)) {
            //System.out.println(modeloAsig.get(listaComAsig.getSelectedIndex()));
            if (c1.getIdCompetencia() == competenciaConID.get(modeloAsig.get(listaComAsig.getSelectedIndex()))) {
                descripcion.setText(c1.getDescripcion());
            }
        }

        if (evt.getClickCount() == 2 && listaComAsig.locationToIndex(evt.getPoint()) != -1) { //doble clic
            index = listaComAsig.locationToIndex(evt.getPoint());

            modeloAct.addElement(modeloAsig.get(index));
            modeloAsig.remove(index);

        }
    }//GEN-LAST:event_listaComAsigMouseClicked

    private void listaComActMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComActMousePressed
        listaComAct = (JList) evt.getSource();
        int index = 0;

        for (Competencia c1 : contCompetencias.getCompetenciasAsignatura().get(asignatura)) {
            if (c1.getIdCompetencia() == competenciaConID.get(modeloAct.get(listaComAct.getSelectedIndex()))) {
                descripcion.setText(c1.getDescripcion());
            }
        }

        if (evt.getClickCount() == 2 && listaComAct.locationToIndex(evt.getPoint()) != -1) { //doble clic
            index = listaComAct.locationToIndex(evt.getPoint());
            modeloAsig.addElement(modeloAct.get(index));
            descripcion.setText("");
            modeloAct.remove(index);

        }
    }//GEN-LAST:event_listaComActMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cargarCompetencias() {
        try {
            contCompetencias.cargarCompetenciasAsignatura(asignatura);
        } catch (SQLException e) {
            System.out.println(e.toString());
        }

        for (int i = 0; i < contCompetencias.getCompetenciasAsignatura().get(asignatura).size(); i++) {
            modeloAsig.addElement(contCompetencias.getCompetenciasAsignatura().get(asignatura).get(i).getNombre());
            competenciaConID.put(contCompetencias.getCompetenciasAsignatura().get(asignatura).get(i).getNombre(), contCompetencias.getCompetenciasAsignatura().get(asignatura).get(i).getIdCompetencia());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextArea descripcion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea lblAyuda;
    private javax.swing.JLabel lblComActuales;
    private javax.swing.JLabel lblComAsig;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombrePrueba;
    private javax.swing.JLabel lblNuevaPrueba;
    private javax.swing.JList<String> listaComAct;
    private javax.swing.JList<String> listaComAsig;
    // End of variables declaration//GEN-END:variables
}
